apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: bzsy
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: bzsy
    app.kubernetes.io/part-of: byoc-app-pjaa
  name: bzsy
spec:
  ports:
  - port: 8081
    targetPort: 8081
  selector:
    app.kubernetes.io/instance: bzsy
status:
  loadBalancer: {}
