apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: bzsy
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: bzsy
    app.kubernetes.io/part-of: byoc-app-pjaa
  name: bzsy
spec:
  rules:
  - host: bzsy-byoc-hjhp-tenant.apps.e2d235fa82a4611d212e.hypershift.aws-2.ci.openshift.org
    http:
      paths:
      - backend:
          service:
            name: bzsy
            port:
              number: 8081
        path: /
        pathType: ImplementationSpecific
status:
  loadBalancer: {}
